name: Code Review

on: [pull_request]

jobs:

  # -- DOCKER -----------------------------------------------------------------
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Run hadolint
        uses: reviewdog/action-hadolint@a588cf93c77060a2836b260c6f0860dc102e8d83 # v1.48.2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
